export const MEDICAL_DOMAINS = [
  "General Medicine",
  "Cardiology",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology",
  "Neurology",
  "Oncology",
  "Pediatrics",
  "Psychiatry",
  "Orthopedics",
  "Ophthalmology",
  "ENT (Otolaryngology)",
  "Gynecology",
  "Urology",
  "Nephrology",
  "Pulmonology",
  "Rheumatology",
  "Dental",
  "Surgery",
  "Psychology",
  "Nutrition & Dietetics",
  "Other"
];
